### ISSUE TITLE
Mekanism fluids will not export out of an ME system

### ISSUE THREAD

**Issue by XxXYaJrAbXxX** [TPPIC/Test-Pack-Please-Ignore-2C#3]
Mekanism fluids such as liquid tritium will no longer import/export out of an ME system. Not sure if this is intended but from my previous version of TPPI2 0.2.6, it used to do so. Anyone able to help with this matter or can confirm this happening?

**Comment by Prospector** [comment]
If it's a bug with the mods, it's probably not gonna get fixed because 1.7 is ancient.

**Comment by XxXYaJrAbXxX** [comment]
Fair enough, will test with gas IO on an ME system

**Comment by XxXYaJrAbXxX** [comment]
Yeah gases don't work either. I have even set the AE2 config for Mekanism integration to be ON not AUTO

**Comment by m4sterP** [comment]
I tried reproducing this error in a new generated world and it did not occur
