### ISSUE TITLE
Updating the World

### ISSUE THREAD

**Issue by mizz141** [TPPIC/Test-Pack-Please-Ignore-2C#4]
Can i Update from 0.2.6 to 1.0.1 Without loosing Anything (Because of Mekanism v9 and other Mods)
Is that somehow Possible or am I just Stupid 
PS: I never Updatet a Modpack Before.

**Comment by XxXYaJrAbXxX** [comment]
Nothing will be lost in the update, however all Mekanism machines will reset their configured sides and also recipes have changed which can affect an ME system if you have auto-crafting set up with that. However, if there are any new ores, they will not generate in previously loaded chunks but can find them in chunks that haven't ever been loaded before. Other than that, updating shouldn't affect anything to remove items or blocks.

**Comment by m4sterP** [comment]
I am also not sure how it is with Forestry, since I did not have the opportunity to test it. Just backup your world before updating.
