### ISSUE TITLE
Mekanism Reactor

### ISSUE THREAD

**Issue by mizz141** [TPPIC/Test-Pack-Please-Ignore-2C#8]
My Mekanism Reactor is sometimes always resetting it Injection Rate... and I just cant figure out why...
Is there some sort of "Base Injection Rate" in the Configs or what?

**Comment by XxXYaJrAbXxX** [comment]
Try redownloading your configs as I couldnt replicate the problem on my
server. The configs might be the incorrect format meaning it could be going to in built
default values.

**Comment by XxXYaJrAbXxX** [comment]
Also what is the version number of the TPPI build?

**Comment by mizz141** [comment]
1.) How do i reloading the configs?

2.) Current Version 1.0.2

**Comment by XxXYaJrAbXxX** [comment]
You delete the mekanism configs in the config folder under the curse launcher save location or ftb launcher save location. Whichever launcher applies to you if on SSP  or on a server it is root folder -> Configs and then delete the mekanism folder/file and run the server.

**Comment by mizz141** [comment]
You can close this now, everything works fine...
